---
title: "Untitled"
output: html_document
date: "2024-02-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r }
library(dplyr)
library(ggplot2)
library (lme4)
library(r2mlm)
library (lmerTest)
library(ivreg)
library(readr)
```

```{r}
popu_poi <- read_tsv ("F:/paper_WORK/masters_thesis_paper/popu_poi.tsv") #data loading 
popu_transit <- read_tsv ("F:/paper_WORK/masters_thesis_paper/popu_transit.tsv")
data_f2 <- read_tsv ("F:/paper_WORK/masters_thesis_paper/ data_f2.tsv")
data_f3 <- read_tsv ("F:/paper_WORK/masters_thesis_paper/ data_f3.tsv")
data_f4 <- read_tsv ("F:/paper_WORK/masters_thesis_paper/ data_f4.tsv")
```

```{r}
#figure 1A
ggplot(popu_poi, aes(x = den_21, y = poi_den)) +
  geom_point(color= "#000080", size =0.01) +
  scale_y_continuous(trans = "log10", labels = scales::comma)+
  scale_x_continuous(trans = "log10", labels = scales::comma)+
  geom_smooth()+
  labs(y = expression ("POI density"~ (Km^-2)), x= expression ("Population density"~ (Km^-2))) +
  theme_classic()+
  theme(axis.title.x = element_text(colour = "#000000",size=12),
        axis.title.y = element_text(colour = "#000000",size=12),
        plot.title = element_text(colour = "#008080",size=22,face="bold"),
        axis.text=element_text(size=10, face="bold")) 
#figure 1B
ggplot(popu_transit, aes(x = den_21, y = transit_per_21)) +
  geom_point(color= "#20b2aa",size= 0.05) +
  scale_y_continuous(labels = scales::percent, limits = c(0, .60), breaks=c(0,.20,.40, .60))+
  scale_x_continuous ( breaks=c(0, 25000, 50000))+
  geom_smooth(color = "tomato")+
  labs(y = "Commute share of transit", x= expression ("Population density"~ (Km^-2))) +
  theme_classic()+
  theme(axis.title.x = element_text(colour = "#000000",size=12),
        axis.title.y = element_text(colour = "#000000",size=10),
        plot.title = element_text(colour = "#008080",size=18,face="bold"),
        axis.text=element_text(size=10, face="bold")
  )
```


```{r}
reg1 <- lmer (l_change ~  pca1_cum2005+ (1|CMA_UID), data_f2)
summary (reg1)#table 1: regression 1
r2mlm (reg1)
```


```{r}
reg2<- lmer (l_change ~ pca1_cum2005+ slope + (1|CMA_UID), data_f2)
summary (reg2) #table 1: regression 2
r2mlm (reg2)
```

```{r}
reg3 <- lmer (l_change ~ pca1_cum2005+ distance_cbd + (1|CMA_UID), data_f2)
summary (reg3)#table 1: regression 3
r2mlm (reg3)
reg4 <- lmer (l_change ~ distance_cbd + (1|CMA_UID), data_f2)
summary (reg4)#table 1: regression 5
r2mlm (reg4)
```

```{r }
reg5 <- lmer (l_change ~  dist_sub_center + pca1_cum2005+ (1|CMA_UID), data_f2)
summary (reg5) #table 1: regression 4
r2mlm (reg5)
reg6 <- lmer (l_change ~  dist_sub_center +  (1|CMA_UID), data_f2)
summary (reg6) #table 1: regression 6
r2mlm (reg6)
```


```{r}
reg7 <- lmer (l_change ~  nearby_sndi + pca1_cum2005+(1|CMA_UID), data_f2)
summary (reg7)#table 1: regression 7
r2mlm (reg7)
reg8 <- lmer (pca1_cum2005 ~  nearby_sndi +(1|CMA_UID), data_f2)
summary (reg8)#table 1: regression 8
r2mlm (reg8)
```



#supplementary 


```{r}
reg01 <- lmer (l_change ~  pca1_cum2005 +  time1+ (1|CMA_UID), data_f2)
summary (reg01)#table S4: regression 1
r2mlm (reg01)
```




```{r}
reg02 <- lmer (l_change ~  pca1_cum2005 +  (1|CMA_UID), data_f3)
summary (reg02)#table S4: regression 2
r2mlm (reg02)
```




```{r}
reg03 <- lmer (l_change ~  pca1_cum2005 +  (1|CMA_UID), data_f4)
summary (reg03)#table S4: regression 3
r2mlm (reg03)
```


```{r}
data_f5 <- data_f2 %>% filter (time1 >20)
reg04 <- lmer (l_change ~  pca1_cum2005 +  (1|CMA_UID), data_f5)
summary (reg04)#table S4: regression 4
r2mlm (reg04)
```

```{r}
reg05<- lm (l_change  ~  slope , data_f2)
summary (reg05)#table S4: regression 5
reg06<- lm (l_change ~  slope +pca1_cum2005, data_f2)
summary (reg06)#table S4: regression 6
reg07 <- ivreg(l_change ~ pca1_cum2005 | slope, data = data_f2)
summary (reg07)#table S4: regression 7
reg08 <- lm (pca1_cum2005 ~ slope, data_f2)
summary (reg08)#table S4: regression 8
```




